version: '3.8'
services:
  semanaddev-postgres:
    image: postgres:15.5-alpine
    platform: linux/x86_64
    container_name: semanaddev-postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

networks:
  default:
    name: semanaddev
    external: true
